### ISSUE TITLE
Is travis_after_all.py still maintained or deprecated?

### ISSUE THREAD

**Issue by ssbarnea** [dmakhno/travis_after_all#17]
Is travis_after_all.py still maintained or deprecated? I am asking this because I see even a very old PR which was not closed.

Is there a better alternative that we should use or it was only the lack of time which make it get less attention?

**Comment by hugovk** [comment]
I've closed that issue.

**Comment by ssbarnea** [comment]
It seems that I am able to merge PRs which means that we are safe, more than one contributor :)
