### ISSUE TITLE
Leaking secure varibles to log

### ISSUE THREAD

**Issue by j1z0** [dmakhno/travis_after_all#24]
There is a potential security issue in this script.  If you have encrypted travis variables, when you execute the command:

export $(cat .to_export_back)

the values of all those encrypted variables will be output to the log.  For example the github access key required to use this script will be leaked.

**Comment by nsuarezml** [comment]
@j1z0 You can try this
 `export $(cat .to_export_back) > /dev/null`

**Comment by hugovk** [comment]
See PR https://github.com/dmakhno/travis_after_all/pull/25.

**Comment by j1z0** [comment]
yup I guess that should have been obvious...

**Comment by jbdeboer** [comment]
Do you have an example of this issue? I know there have been similar problems in the past, but I'm not sure I follow this one.
