### ISSUE TITLE
is that repo abandonware?

### ISSUE THREAD

**Issue by ssbarnea** [dmakhno/travis_after_all#7]
While I found the travis_after_all of great use it seems that bugs and issue requests are ignored and the current version seems to be broken.

If you do not have time to take care of it please add few other contributors to it so we can maintain it.

It seems that now the `$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS` are empty even if I followed the guide.

https://travis-ci.org/pycontribs/jira/jobs/71114809

**Comment by dmakhno** [comment]
@ssbarnea, @hugovk, @jmcarp, @jbdeboer, you are all contributors. I'm sure you know what you do AND what you merge.

Unfortunately I haven't used travis for a while and messed up with github notifications, that is something going on here.

**Comment by ssbarnea** [comment]
Thank you @dmakhno, a really nice move!

**Comment by jbdeboer** [comment]
If you send a PR to jbdeboer/travis_after_all, I can maintain it there.
